name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Cargo Build
      run: cargo build --verbose
    - name: Wasm Build 
      run: wasm-pack build --target web
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.1
      with:
        # GitHub token
        token: ${{ github.token }} # default is ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        timeout: 600000 # optional, default is 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        error_count: 10 # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        reporting_interval: 5000 # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: github-pages # optional, default is github-pages
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        preview: false # optional, default is false
